server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  JwtSecretKey: secretkey
  SigningKey: QUSHIFT
  TokenTTL: 86400
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgrespw
  PostgresqlDbname: auth
  PostgresqlSslmode: false
  PgDriver: pgx